---
title: "Figure 4 Construction"
author: "Anthony R Cillo"
date: "March 6 2025"
output: html_document
---

## Load packages

```{r}

library(tidyverse)
library(ggplot2)
library(patchwork)
library(here)

```

## Load data

```{r}

umap_meta <- readRDS("../../01_input/SARC028_combined_umap_meta_CosMx_scRNAseq.rds")

dat_comb_meta <- readRDS("../../01_input/SARC028_CosMx_meta_cell_positions.rds")

```

## Plot scRNAseq/CosMx integrated UMAPs

```{r}

umap_meta$final_cell_annot <- gsub("_"," ",umap_meta$final_cell_annot)
umap_meta$final_cell_annot <- gsub("pos","\\+",umap_meta$final_cell_annot)
umap_meta$final_cell_annot <- as.factor(umap_meta$final_cell_annot)

custom_cols <- colorRampPalette(RColorBrewer::brewer.pal("Set2",n=8))(length(levels(umap_meta$final_cell_annot)))
cell_names <- levels(umap_meta$final_cell_annot)

p1 <- umap_meta %>%
  filter(data_type=="scrnaseq") %>% 
  ggplot(.) +
  geom_point(aes(x=UMAP_1,y=UMAP_2),colour="black",size=3) +
  geom_point(aes(x=UMAP_1,y=UMAP_2,colour=final_cell_annot),size=1.5,show.legend = TRUE) +
  scale_color_manual(values=custom_cols,labels=cell_names,drop=FALSE) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none")

p2 <- umap_meta %>%
  filter(data_type=="nanostring") %>% 
  filter(UMAP_1<6) %>% 
  ggplot(.) +
  geom_point(aes(x=UMAP_1,y=UMAP_2),colour="black",size=3) +
  geom_point(aes(x=UMAP_1,y=UMAP_2,colour=final_cell_annot),size=1.5,show.legend=TRUE) +
  scale_color_manual(values=custom_cols,labels=cell_names,
                     drop=FALSE) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position="none")

p2x <- umap_meta %>%
  filter(data_type=="scrnaseq") %>% 
  mutate(`Cell types`=final_cell_annot) %>% 
  ggplot(.) +
  geom_point(aes(x=UMAP_1,y=UMAP_2),colour="black",size=3) +
  geom_point(aes(x=UMAP_1,y=UMAP_2,colour=`Cell types`),size=1.5,show.legend = TRUE) +
  scale_color_manual(values=custom_cols,labels=cell_names,drop=FALSE) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  guides(colour=guide_legend(ncol=1))

legend <- cowplot::get_legend(p2x)
p2_l <- ggplotify::as.ggplot(legend)

```

## Plot positions of cells from CosMx

```{r}

p3 <- dat_comb_meta %>%
  mutate(group_info=paste(fov,cellID,sep="_")) %>% 
  ggplot(.,aes(x=y_global_px,y=x_global_px,group=group_info)) +
  geom_polygon() +
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        legend.position="none")

p4 <- dat_comb_meta %>%
  mutate(group_info=paste(fov,cellID,sep="_")) %>% 
  filter(fov=="1") %>% 
  ggplot(.,aes(x=y_global_px,y=x_global_px,group=group_info)) +
  geom_polygon(colour="red") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position="none") +
  xlab("X location") +
  ylab("Y location")

p5 <- dat_comb_meta %>%
  mutate(group_info=paste(fov,cellID,sep="_")) %>% 
  ggplot(.) +
  geom_polygon(aes(x=y_global_px,y=x_global_px,group=group_info,fill=final_cell_annot),show.legend=TRUE) +
  scale_fill_manual(values=custom_cols,labels=cell_names,drop=FALSE) +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        axis.text=element_blank(),
        axis.title=element_blank(),
        legend.position="none") +
  xlab("X location") +
  ylab("Y location")

p6 <- dat_comb_meta %>%
  mutate(final_cell_annot=as.factor(final_cell_annot)) %>% 
  filter(fov==1) %>% 
  filter(!is.na(final_cell_annot)) %>% 
  mutate(group_info=paste(fov,cellID,sep="_")) %>% 
  ggplot(.) +
  geom_polygon(aes(x=y_global_px,y=x_global_px,group=group_info,fill=final_cell_annot),colour="black",show.legend=TRUE) +
  scale_fill_manual(values=custom_cols,labels=cell_names,drop=FALSE) +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        axis.text=element_blank(),
        legend.position="none") +
  xlab("X location") +
  ylab("Y location")

```

## Show components of plot

```{r}
p1
p2
p3
p4
p5
p6 
```