---
title: "Figure 6 Construction"
author: "Anthony R Cillo"
date: "March 6 2025"
output: md_document
---

## Load packages

```{r}

.libPaths("/ix1/acillo/arc85/packages/Rlibs_sarc028")

library(tidyverse)
library(ggplot2)
library(patchwork)
library(here)

```

## Load data

```{r}

cosmx_gene_sets <- readRDS("../../01_input/SARC028_CosMx_gene_sets_results.rds")
dat_comb_meta <- readRDS("../../01_input/SARC028_CosMx_meta_cell_positions.rds")

cosmx_spatial_clusters <- cosmx_gene_sets %>%
  select(cb,spatial_clusters)

dat_comb_meta <- left_join(dat_comb_meta,cosmx_spatial_clusters,by="cb")
dat_comb_meta$spatial_clusters <- as.factor(dat_comb_meta$spatial_clusters)

```

## Cell location neighborhood plots for responder and non-responder 

```{r}

custom_cols <- colorRampPalette(RColorBrewer::brewer.pal("Set2",n=8))(10)
cluster_names <- levels(dat_comb_meta$spatial_clusters)
names(custom_cols) <- cluster_names

p1 <- dat_comb_meta  %>%
  mutate(group_info=paste(fov_selected,cb,sep="_")) %>% 
  filter(fov_selected=="20") %>% 
  ggplot(.,aes(x=y_global_px,y=x_global_px,group=group_info,fill=spatial_clusters)) +
  geom_polygon(colour="black") +
  scale_fill_manual(values=custom_cols) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position="none") +
  xlab("X location") +
  ylab("Y location") +
  ggtitle("Patient 9 post-treatment\nStable disease")

p2 <- dat_comb_meta  %>%
  mutate(group_info=paste(fov,cellID,sep="_")) %>% 
  filter(fov=="20") %>% 
  select(spatial_clusters) %>%
  mutate(total_cells=n()) %>%
  group_by(spatial_clusters) %>%
  mutate(hood_counts=n()) %>%
  ungroup() %>%
  mutate(hood_freq=hood_counts/total_cells) %>%
  distinct() %>%
  ggplot(.,aes(x=1,y=hood_freq,fill=spatial_clusters)) +
  geom_col() +
  scale_fill_manual(values=custom_cols) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position="none") +
  xlab("") +
  ylab("Frequency of cell neighorhood")

p3 <- dat_comb_meta  %>%
  mutate(group_info=paste(fov,cellID,sep="_")) %>% 
  filter(fov=="17") %>% 
  ggplot(.,aes(x=y_global_px,y=x_global_px,group=group_info,fill=spatial_clusters)) +
  geom_polygon(colour="black") +
  scale_fill_manual(values=custom_cols) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position="none") +
  xlab("X location") +
  ylab("Y location") +
  ggtitle("Patient 2 Baseline\nProgressive disease")

p4 <- dat_comb_meta  %>%
  mutate(group_info=paste(fov,cellID,sep="_")) %>% 
  filter(fov=="17") %>% 
  select(spatial_clusters) %>%
  mutate(total_cells=n()) %>%
  group_by(spatial_clusters) %>%
  mutate(hood_counts=n()) %>%
  ungroup() %>%
  mutate(hood_freq=hood_counts/total_cells) %>%
  distinct() %>%
  ggplot(.,aes(x=1,y=hood_freq,fill=spatial_clusters)) +
  geom_col() +
  scale_fill_manual(values=custom_cols) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position="none") +
  xlab("") +
  ylab("Frequency of cell neighorhood")

```

## Plotting gene set scores 

```{r}

## Plotting
cosmx_gene_sets $final_cell_annot <- as.factor(cosmx_gene_sets $final_cell_annot)

custom_cols2 <- colorRampPalette(RColorBrewer::brewer.pal("Set2",n=8))(length(levels(cosmx_gene_sets $final_cell_annot)))
cell_names <- levels(cosmx_gene_sets $final_cell_annot)
names(custom_cols2) <- cell_names

p5 <- cosmx_gene_sets %>%
  filter(final_cell_annot %in% c("Tumor_cells_c5","Tumor_cells_c4","Tumor_cells_c1")) %>%
  ggplot(.,aes(x=final_cell_annot,y=scale(KINSEY_TARGETS_OF_EWSR1_FLII_FUSION_UP))) +
  geom_violin(aes(fill=final_cell_annot)) +
  geom_boxplot(width=0.2,outlier.shape=NA) +
  scale_fill_manual(values=custom_cols2) +
  theme_bw() + 
  theme(axis.text.x=element_text(angle=45,hjust=T),
        legend.position="none") +
  xlab("") +
  ylab("Targets of EWSR1/FLI1 Fusion\n(scaled enrichment)")

p6 <- cosmx_gene_sets %>%
  filter(final_cell_annot %in% c("Tumor_cells_c5","Tumor_cells_c4","Tumor_cells_c1")) %>%
  ggplot(.,aes(x=final_cell_annot,y=scale(HALLMARK_TGF_BETA_SIGNALING))) +
  geom_violin(aes(fill=final_cell_annot)) +
  geom_boxplot(width=0.2,outlier.shape=NA) +
  scale_fill_manual(values=custom_cols2) +
  theme_bw() + 
  theme(axis.text.x=element_text(angle=45,hjust=T),
        legend.position="none") +
  xlab("") +
  ylab("Hallmark TGF-b signaling\n(scaled enrichment)")

p7 <- cosmx_gene_sets %>%
  filter(final_cell_annot %in% c("Tumor_cells_c5","Tumor_cells_c4","Tumor_cells_c1")) %>%
  ggplot(.,aes(x=final_cell_annot,y=scale(HLA_signature))) +
  geom_violin(aes(fill=final_cell_annot)) +
  geom_boxplot(width=0.2,outlier.shape=NA) +
  scale_fill_manual(values=custom_cols2) +
  theme_bw() + 
  theme(axis.text.x=element_text(angle=45,hjust=T),
        legend.position="none") +
  xlab("") +
  ylab("HLA class I expression\n(scaled enrichment)")

p8 <- cosmx_gene_sets %>%
  filter(final_cell_annot %in% c("Tumor_cells_c5","Tumor_cells_c4","Tumor_cells_c1")) %>%
  ggplot(.,aes(x=final_cell_annot,y=scale(HALLMARK_INTERFERON_ALPHA_RESPONSE))) +
  geom_violin(aes(fill=final_cell_annot)) +
  geom_boxplot(width=0.2,outlier.shape=NA) +
  scale_fill_manual(values=custom_cols2) +
  theme_bw() + 
  theme(axis.text.x=element_text(angle=45,hjust=T),
        legend.position="none") +
  xlab("") +
  ylab("Hallmark IFN-a response\n(scaled enrichment)")

```

## Overall immune infiltrate by hoods 

```{r}

p9 <- cosmx_gene_sets %>%
  select(fov_selected,HLA_signature,final_cell_annot) %>%
  group_by(fov_selected) %>%
  mutate(total_cells=n()) %>%
  mutate(hla_mean=mean(HLA_signature)) %>%
  select(-HLA_signature) %>%
  ungroup() %>%
  mutate(immune_cell=ifelse(!grepl("Tumor|Osteoclasts",final_cell_annot),"Immune","Non-immune")) %>%
  filter(immune_cell=="Immune") %>%
  group_by(fov_selected) %>%
  mutate(immune_counts=n()) %>%
  ungroup() %>%
  mutate(immune_freq=immune_counts/total_cells) %>%
  select(fov_selected,hla_mean,immune_freq) %>%
  distinct() %>%
  ggplot(.,aes(x=scale(hla_mean),y=immune_freq)) +
  geom_point() +
  theme_bw() +
  xlab("HLA class I expression\n(scaled enrichment)") +
  ylab("Immune cell infiltration\n(percent of total cells)")

infil_stats <- cosmx_gene_sets %>%
  select(fov_selected,HLA_signature,final_cell_annot) %>%
  group_by(fov_selected) %>%
  mutate(total_cells=n()) %>%
  mutate(hla_mean=mean(HLA_signature)) %>%
  select(-HLA_signature) %>%
  ungroup() %>%
  mutate(immune_cell=ifelse(!grepl("Tumor|Osteoclasts",final_cell_annot),"Immune","Non-immune")) %>%
  filter(immune_cell=="Immune") %>%
  group_by(fov_selected) %>%
  mutate(immune_counts=n()) %>%
  ungroup() %>%
  mutate(immune_freq=immune_counts/total_cells) %>%
  select(fov_selected,hla_mean,immune_freq) %>%
  distinct()

cor.test(infil_stats$hla_mean,infil_stats$immune_freq,method="spearman")

p10 <- cosmx_gene_sets %>%
  filter(final_cell_annot %in% c("Tumor_cells_c5","Tumor_cells_c4","Tumor_cells_c1")) %>%
  select(fov_selected,HALLMARK_INTERFERON_GAMMA_RESPONSE,HLA_signature,final_cell_annot) %>%
  group_by(fov_selected) %>%
  mutate(ifna_mean=mean(HALLMARK_INTERFERON_GAMMA_RESPONSE)) %>%
  select(-HALLMARK_INTERFERON_GAMMA_RESPONSE) %>%
  mutate(hla_mean=mean(HLA_signature)) %>%
  select(-HLA_signature) %>%
  distinct() %>%
  ggplot(.,aes(x=scale(hla_mean),y=scale(ifna_mean))) +
  geom_point() +
  theme_bw() +
  xlab("HLA class I expression\n(scaled enrichment)") +
  ylab("Hallmark IFN-gamma response\n(scaled enrichment)")

ifn_hla_stats <- cosmx_gene_sets %>%
  filter(final_cell_annot %in% c("Tumor_cells_c5","Tumor_cells_c4","Tumor_cells_c1")) %>%
  select(fov_selected,HALLMARK_INTERFERON_GAMMA_RESPONSE,HLA_signature,final_cell_annot) %>%
  group_by(fov_selected) %>%
  mutate(ifng_mean=mean(HALLMARK_INTERFERON_GAMMA_RESPONSE)) %>%
  select(-HALLMARK_INTERFERON_GAMMA_RESPONSE) %>%
  mutate(hla_mean=mean(HLA_signature)) %>%
  select(-HLA_signature) %>%
  distinct()

cor.test(ifn_hla_stats$hla_mean,ifn_hla_stats$ifng_mean,method="spearman")

```

## Statistics

```{r}

cosmx_gene_sets %>%
  filter(final_cell_annot %in% c("Tumor_cells_c5","Tumor_cells_c4","Tumor_cells_c1")) %>%
  select(final_cell_annot,KINSEY_TARGETS_OF_EWSR1_FLII_FUSION_UP,HALLMARK_TGF_BETA_SIGNALING,HLA_signature,HALLMARK_INTERFERON_ALPHA_RESPONSE) %>%
  distinct() %>%
  gather(gene_set,values,-final_cell_annot) %>% 
  split(.$gene_set) %>%
  map(~lm(values~final_cell_annot,data=.)) %>%
  map(~summary(.))

cosmx_gene_sets %>%
  filter(final_cell_annot %in% c("Tumor_cells_c5","Tumor_cells_c4","Tumor_cells_c1")) %>%
  select(final_cell_annot,KINSEY_TARGETS_OF_EWSR1_FLII_FUSION_UP,HALLMARK_TGF_BETA_SIGNALING,HLA_signature,HALLMARK_INTERFERON_ALPHA_RESPONSE) %>%
  distinct() %>%
  gather(gene_set,values,-final_cell_annot) %>% 
  split(.$gene_set) %>%
  map(~pairwise.wilcox.test(.$values,.$final_cell_annot,data=.))

```

## Show figure components

```{r}

p1
p2
p3
p4
p5
p6
p7
p8
p9
p10

```

## Session info

```{r}

sessionInfo()

```
